services:
  - type: web
    name: fastapi-db-test
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_HOST
        value: "your_database_host"
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        value: "your_database_name"
      - key: DATABASE_USER
        value: "your_database_user"
      - key: DATABASE_PASSWORD
        value: "your_database_password"
