services:
  - type: web
    name: fastapi-db-test
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_HOST
        value: "localhost"
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        value: "test_db"
      - key: DATABASE_USER
        value: "test_user"
      - key: DATABASE_PASSWORD
        value: "test"
